### ISSUE TITLE
consider color matching in CIE LAB space or CIE2000

### ISSUE THREAD

**Issue by dylanbeaudette** [ryantimpe/LEGOMosaics#1]
First of all this is just amazing. Congratulations on doing what many lego fans often dream about doing.

I am not sure, but I suspect that the [lego colors](https://github.com/ryantimpe/LEGOMosaics/blob/master/Colors/Lego_Colors.csv) are likely in the [sRGB](https://en.wikipedia.org/wiki/SRGB) colorspace. This is a convenient color space for displaying colors on a screen but not the most accurate space to perform color matching. Would you be interested in using the [CIELAB](https://en.wikipedia.org/wiki/CIELAB_color_space) color space, or even better [CIE2000](https://en.wikipedia.org/wiki/Color_difference#CIEDE2000) color distance metric? The CIELAB space is based on (typical) human perception of color and matching done in this color space is usually more realistic. It may not matter when working with a small palette of highly saturated colors but it might be worth a try.

There are a couple of ways to convert colors in R, my favorites are `grDevices::convertColor()` and `farver::convert_colour()`. Note that each specify the source color space in a slightly different manner, `RGB` is typically used to describe a family of color spaces while `sRGB` is quite specific to uncalibrated computer screens, HTML colors, and so on.

Here is a rather verbose example, based on a color system (Munsell) and methods used in soil science and geology.

```r
library(aqp)
library(farver)

# lego colors
# assuming these are sRGB / D65 colors
legos <- read.csv('https://github.com/ryantimpe/LEGOMosaics/raw/master/Colors/Lego_Colors.csv', stringsAsFactors = FALSE)

# convert
legos.sRGB <- legos[, c('R', 'G', 'B')] / 255
leogs.LAB <- convert_colour(legos.sRGB, from = 'rgb', to = 'lab', white_from = 'D65', white_to = 'D65')

# sort colors based on distances in CIE LAB spacec
previewColors(rgb(legos.sRGB))

# test conversion to Munsell
rgb2munsell(legos.sRGB)

# color to match, result is sRGB
x <- parseMunsell('10YR 3/4', return_triplets=TRUE)

# compare example color to all lego colors via CIE2000
d <- compare_colour(from=x, to=legos.sRGB, from_space='rgb', to_space = 'rgb', method='cie2000')

# sort lego colors based on CIE2000 distances from exmaple color
previewColors(rgb(legos.sRGB), col.order=order(d), method='manual')

# check closest (perceptual) color
idx <- which.min(d)
legos[idx, ]

# back-transform to Munsell
rgb2munsell(legos.sRGB[idx, ])
```

You might be able to guess why this would be *interesting* to earth scientists.

**Comment by ryantimpe** [comment]
I definitely like keeping the project restricted to R packages already used by most people (dplyr, purrr, etc) but will try this out when I get a chance. I can see this helping with shadows getting assigned to a completely new color and speeding up the functions.

**Comment by dylanbeaudette** [comment]
In that case, Euclidean distance in CIE LAB via `grDevices::convertColor()` would keep the dependencies to a minimum.

**Comment by dylanbeaudette** [comment]
Another idea: image resampling can be done using the `raster` package in about 1 line of code. Just a thought. Incidentally, I had to install the `tidyverse` package.

**Comment by ryantimpe** [comment]
Revisiting this...

**Comment by ryantimpe** [comment]
Thanks for this. Ended up using the compare_color() function in farver. CEI94 looks best in general, though depends on the composition of the image. Leaving the original euclidean distance calculation in there as an alternative. 

This is updated on the other branch. Will likely merge in August or September.

**Comment by dylanbeaudette** [comment]
Thanks for considering. 

I'm curious as to how "best" is defined--color matching is a tricky thing. I have found that [CIE DE2000](https://en.wikipedia.org/wiki/Color_difference#CIEDE2000) has been the most universally "reasonable" in the realm of soil science and field description of soil color. Either metric will be far more "realistic" than Euclidean distance in sRGB.

**Comment by ryantimpe** [comment]
Here are a few comparisons. CIE2000 seems like it loses some of the depth of the image. Overall, I'm happy that these options fix the problems with whites turning into light blue and light pink.

![colorspace_unicorn](https://user-images.githubusercontent.com/8763398/61834124-a9b91900-ae44-11e9-96be-9a138356b784.png)
![colorspace_bobcat](https://user-images.githubusercontent.com/8763398/61834125-a9b91900-ae44-11e9-89c0-6b3093e6b3c2.png)
![colorspace_flower](https://user-images.githubusercontent.com/8763398/61834126-a9b91900-ae44-11e9-8374-b475868b7374.png)
![colorspace_me](https://user-images.githubusercontent.com/8763398/61834127-a9b91900-ae44-11e9-9aa0-11895dbdb9a4.png)

**Comment by dylanbeaudette** [comment]
Nice! An excellent way to compare the results, thanks for the demo. I wonder if "depth" (contrast?) can be enhanced by using a 2-step process:
   1. reduce original colors to a limited palette of 8-16 colors, via k-means
   2. match legos to the reduced palette via CIE color difference

Beyond that, a simple [dithering](https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering) step might be useful.

Too much?
