### ISSUE TITLE
Difficult to install

### ISSUE THREAD

**Issue by FrancyJGLisboa** [ryantimpe/LEGOMosaics#10]
It is difficult to install. I got an error using devtools::install_github saying that the glue package can't be unloaded. I don't understand if even after install the glue package I kept getting the same error message.

Any tip?
Thanks for your fantastic work.

**Comment by ryantimpe** [comment]
Not sure about this specific issue, but perhaps check to see if you have any other instances of R or RStudio open, and then close them?
