### ISSUE TITLE
display_bricks() not found

### ISSUE THREAD

**Issue by GeoMicroSoares** [ryantimpe/LEGOMosaics#14]
Hi there,

Getting a weird one with a newly installed (```devtools::install_github("ryantimpe/brickr")```) version of `brickr`. Can't seem to find ```display_bricks``` apparently.

Reproducible (?) example from the Github repository:

``` 
library(brickr)
 
#This is a brick
brick <- data.frame(
     Level="A",
     X1 = rep(1,4),
     X2 = rep(1,4)
 )
 
brick %>% 
    bricks_from_table() %>% 
    display_bricks()
```

And what I'm getting:

``` Error in display_bricks(.) : could not find function "display_bricks"```` ```

Thanks in advance!

**Comment by ryantimpe** [comment]
I've changed any graphics-rendering function to "build_*()" in the latest release. So use build_bricks() instead.

Is that example from any current documentation? I'll need to update it.
