### ISSUE TITLE
Piece list appears inflated

### ISSUE THREAD

**Issue by schnee** [ryantimpe/LEGOMosaics#2]
This is a really fun package.

```
  mosaic1 <- readJPEG("Images/goldengirls.JPG") %>% 
  scale_image(c(48)) %>%
  legoize() %>% 
  collect_bricks() 

area <- tibble(
  Brick_size = c("1 x 1", "2 x 1", "3 x 1", "4 x 1", "2 x 2", "4 x 2"),
  area = c(1, 2, 3, 4, 4, 8),
)

areas <- mosaic1$pieces %>%
  left_join(area)
  
areas %>% 
  # per row area
  mutate(per_row_area = n * area) %>% 
  # total area of the piece list
  summarize(sum(per_row_area))
```

this returns a total piecewise area of 2748, but 48*48 = 2304

A visual inspection of a 32x32 Golden Girl inflates the bright purple 4x2 count (I manually count 8, but table_pieces returns 10).

**Comment by ryantimpe** [comment]
Thanks! Just pushed the update. Had to change my calculation on which brick each stud belongs to. Area checks should be good now.
