### ISSUE TITLE
I broke brickr with tidyr 1.1.1 😢

### ISSUE THREAD

**Issue by hadley** [ryantimpe/LEGOMosaics#37]
The problem is this code:

```R
brick_sizes <- tibble::tibble(bricks = use_bricks) %>% 
  tidyr::separate(bricks, c("xx", "yy"), sep = "[^[\\d+]]+") %>% 
  dplyr::mutate_all(as.numeric)
```

Which no longer works because I've changed regular expression engines. I'm not sure what you're trying to do here so I couldn't fix myself, but if you explain what you're trying to express with `[^[\\d+]]+` I can suggest a regexp that works.

**Comment by ryantimpe** [comment]
On it. Thanks!

**Comment by hadley** [comment]
BTW if you're just trying to match any number of non-digits, `"\\D+"` should do the job.

**Comment by ryantimpe** [comment]
Yeah that fixed it. Thanks.
