### ISSUE TITLE
collaborate on package creation?

### ISSUE THREAD

**Issue by rpodcast** [ryantimpe/LEGOMosaics#4]
Like many others in the R community I am so inspired by your efforts on creating these mosaics!  I am actually in the process of creating a shiny app that serves as a frontend to these functions along with some other enhancements, and it would be great to have your functions available as a package.  I've begun some exploratory conversions to a package format and I'd be more than happy to send a PR with what I've done thus far if you are interested?

**Comment by ryantimpe** [comment]
That's awesome! I'm also in the process of putting the functions into a package. How about you give me a few days to wrap that up and push it? Then I'm happy to collaborate from there.

**Comment by rpodcast** [comment]
Sounds like a plan!  I'll keep an eye out and look forward to our collaboration :+1:

**Comment by rpodcast** [comment]
Looking great!  I'll create separate issues for ideas/features I have in mind.
