### ISSUE TITLE
Where did geom_brick_col() go? 😞

### ISSUE THREAD

**Issue by gsimchoni** [ryantimpe/LEGOMosaics#40]
Hi Ryan,

Big fan of this package. Wondering where `geom_brick_col()`, `scale_fill_brick()`, `coord_brick()` and `theme_brick()` go?

(I want to reproduce a barchart similar to [this](http://brickr.org/reference/geom_brick_col.html) in v0.2.0)

If they can't return do you know how I can write them on my own or have some kind of a gist lying around?

Thanks!

**Comment by ryantimpe** [comment]
The ggplot functions were super buggy so I'm working on a write but it's slow-going. I'll send you an invite to the other repo. Still a WIP but might help out.

**Comment by ryantimpe** [comment]
Here you go. You should also have access to the repo too with the WIP package.
https://gist.github.com/ryantimpe/c382c193f5c13da729ebc9948f4b2a4f

This was an example I made for someone else a few months ago, but should show some of the basics.

**Comment by gsimchoni** [comment]
Thank you Ryan! (again, big fan)
