### ISSUE TITLE
404 errors on blog posts

### ISSUE THREAD

**Issue by alexpreynolds** [ryantimpe/LEGOMosaics#5]
I was curious to know more about your project, but the following links from the README gave 404 errors:

• http://www.ryantimpe.com/2018/04/23/lego-mosaic1/
• http://www.ryantimpe.com/2018/05/07/lego-mosaic2/

Fun tool! My pug looks amazing in LEGO form.

**Comment by ryantimpe** [comment]
I updated my website and accidentally broke the blog links. I should have a new README up early next week with the package release. Until then...

- http://www.ryantimpe.com/post/lego-mosaic1/
- http://www.ryantimpe.com/post/lego-mosaic2/
